airbnb_analytics_platform:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "md:{{ env_var('MOTHERDUCK_DATABASE', 'airbnb_analytics') }}"
      schema: "{{ env_var('DBT_TARGET_SCHEMA', 'main') }}"
      threads: 4

    local:
      type: duckdb
      path: "{{ env_var('DUCKDB_LOCAL_PATH', 'airbnb_analytics.duckdb') }}"
      schema: "{{ env_var('DBT_TARGET_SCHEMA', 'main') }}"
      threads: 4
